### PR TITLE
Replace 'Stream.collect(Collectors.toList())' with 'Stream.toList()'

### LINKED ISSUE #43: Replace 'Stream.collect(Collectors.toList())' with 'Stream.toList()'
There is a [code smell](https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=paion-data_astraios&open=AYqMSaB-qpE7yGoVUyZd) that can be fixed pretty quickly

### PR DESCRIPTION
**Pull request by WordlessEcho**
Changelog
---------

### Fixed
Fixes #43

### Security

Checklist
---------

- [ ] Test
- [ ] Self-review
- [ ] Documentation

### CODE REVIEW

**Comment by WordlessEcho** [comment]
I am unable to run all tests because of this problem: #65

**Comment by QubitPi** [comment]
> I am unable to run all tests because of this problem: #65

Hi @WordlessEcho , thank you for openning this PR. #65 should not be a problem (please see the comments there).

There seems to be, however, another issue unrelated to yours. We will come back to this PR in a moment

**Comment by WordlessEcho** [comment]
@QubitPi Could you please re-run CI testing?

**Comment by WordlessEcho** [comment]
```log
Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project astraios: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator -> [Help 1]
```

**Comment by QubitPi** [comment]
@WordlessEcho I have approved this PR. Thank you! 👍🏻 

The previous run indicates that _all tests passed_, which is why I approved. But looks like [sonar scan cannot run on fork](https://community.sonarsource.com/t/sonar-cannot-be-run-on-pr-from-a-fork/69229/2). 

We are going to [disable sonar on fork](https://github.com/paion-data/astraios/pull/67) now and let this PR go through as soon as possible. 

When you do another rebase to check this in, we will merge your PR sooner rather than later

**Review by QubitPi — APPROVED** [review]

**Comment by QubitPi** [comment]
Although this PR becomes temporarily obsolete, it helped us by letting us thinking about passig args to 3rd-party library. See https://github.com/paion-data/astraios/issues/43#issuecomment-1833238472 comments for details

**Pull request closed without merging**
